# Generated by Django 3.0 on 2020-01-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
