# Generated by Django 3.0 on 2020-01-13 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_clan_player'),
        ('profiles', '0002_auto_20200111_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='player_id',
            new_name='wgid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='clan_tag',
        ),
        migrations.AddField(
            model_name='profile',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Player'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clan_id',
            field=models.IntegerField(null=True),
        ),
    ]
