# Generated by Django 3.0 on 2020-01-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='ship_upgrades',
        ),
    ]
