# Generated by Django 3.0 on 2020-01-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_ship_ship_upgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_picture_url',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_tier',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
