# Generated by Django 3.0 on 2020-01-13 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_skill_skill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_wgid', models.IntegerField()),
                ('clan_tag', models.CharField(max_length=10)),
                ('clan_name', models.CharField(max_length=50)),
                ('clan_members_count', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_wgid', models.IntegerField()),
                ('player_nickname', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('player_clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Clan')),
            ],
        ),
    ]
