# Generated by Django 3.0 on 2020-01-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_clan_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_nickname',
        ),
    ]
