# Generated by Django 3.0 on 2020-01-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_player_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='clan_realm',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
