# Generated by Django 3.0 on 2020-01-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_clan_clan_realm'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_ships',
            field=models.ManyToManyField(to='data.Ship'),
        ),
        migrations.CreateModel(
            name='ShipInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipinstance_main_battery_hits', models.IntegerField()),
                ('shipinstance_main_battery_shots', models.IntegerField()),
                ('shipinstance_xp', models.IntegerField()),
                ('shipinstance_battles', models.IntegerField()),
                ('shipinstance_torpedoes_hits', models.IntegerField()),
                ('shipinstance_torpedoes_shots', models.IntegerField()),
                ('shipinstance_wins', models.IntegerField()),
                ('shipinstance_losses', models.IntegerField()),
                ('shipinstance_damage_dealt', models.IntegerField()),
                ('shipinstance_potential_damage', models.IntegerField()),
                ('shipinstance_spotting_damage', models.IntegerField()),
                ('shipinstance_cb_battles', models.IntegerField(default=0)),
                ('shipinstance_cb_wins', models.IntegerField(default=0)),
                ('shipinstance_cb_battles_survived', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('shipinstance_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player')),
                ('shipinstance_ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Ship')),
            ],
        ),
    ]
