# Generated by Django 3.0 on 2020-01-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
        ('data', '0008_auto_20200113_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_clan_role',
            field=models.CharField(default='private', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='player_userclan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clan.UserClan'),
        ),
    ]
