# Generated by Django 3.0 on 2020-01-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200114_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_clan_role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_ships',
            field=models.ManyToManyField(null=True, to='data.Ship'),
        ),
    ]
