# Generated by Django 3.0 on 2020-01-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200114_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_joined_at',
            field=models.DateTimeField(null=True),
        ),
    ]
