# Generated by Django 3.0 on 2020-01-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_player_player_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_battles',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_damage_dealt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_main_battery_hits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_main_battery_shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_potential_damage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_spotting_damage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_torpedoes_hits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_torpedoes_shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipinstance',
            name='shipinstance_xp',
            field=models.IntegerField(null=True),
        ),
    ]
