# Generated by Django 3.0 on 2020-01-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200114_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_joined_at',
            field=models.IntegerField(null=True),
        ),
    ]
