# Generated by Django 3.0 on 2020-01-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claninstance',
            name='claninstance_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
