# Generated by Django 3.0 on 2020-01-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_battles', '0002_claninstance_claninstance_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinstance',
            name='playerinstance_survived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
